-- AlterTable
ALTER TABLE "HeroSlide"
ADD COLUMN     "desktopAspectRatio" TEXT NOT NULL DEFAULT '16/9',
ADD COLUMN     "desktopFocalX" DOUBLE PRECISION NOT NULL DEFAULT 50,
ADD COLUMN     "desktopFocalY" DOUBLE PRECISION NOT NULL DEFAULT 50;
